### PR TITLE
Update de_de.nhloc

### PR DESCRIPTION
**Pull request by temran**
Some corrections in the help-text

### CODE REVIEW

**Comment by joostn** [comment]
Danke!

**Comment by temran** [comment]
Hi Joost,

a special case which cannot be solved in GitHub:


3447 "id": "txt.unknownormanuallens",
3448 "txt": "Unbekanntes oder manuelles Objektiv"

This cannot be inserted in:

"Diese Daten immer verwenden für *Unbekanntes* oder manuelles Objektiv
auf..."

Correction:

"Diese Daten immer verwenden für *unbekanntes* oder manuelles Objektiv
auf..."


--- unbekanntes oder manuelles ---


Best regards

Harald

Am Mo., 5. Nov. 2018 um 11:45 Uhr schrieb joostn <notifications@github.com>:

**Comment by joostn** [comment]
Not a big deal if you ask me, let's just leave this as it is..

**Comment by temran** [comment]
Oh, I thought it woud be no big deal for you to code a new line. I tried
coding many years ago and was upset that a single wrong character could
destroy a running program.
This can be the same in language. A single "i or I" can change the meaning:
"Die Admins löschen *ihre* Daten" - "The admins delete their data." or
"Die Admins löschen *Ihre* Daten" - The admins are deleting your data."

"Diese Dateien immer verwenden für *Unbekanntes*..."   If you read this,
"Unbekanntes" is a noun in German. "Unbekanntes"- All which is unknown.

It defenitly makes more sense to write: "Diese Daten immer verwenden
für unbekanntes oder manuelles Objektiv auf..."

I really would be glad if you would fix this.

Am Di., 6. Nov. 2018 um 09:57 Uhr schrieb joostn <notifications@github.com>:

**Comment by joostn** [comment]
Ah, I understand now. If it changes the meaning it's not good. Thanks for refreshing my german :-)

I've uncapitalized them:

https://github.com/newhousenl/ptgui_localization/commit/23e0a9163d122d4a5a9b76f6a507a8b62edeed6d

PTGui (next version) will capitalize these strings in places where it is necessary (when the string appear as an item in a dropdown list, and under 'EXIF' in the lens settings tab).
Thanks

**Comment by joostn** [comment]
BTW, fisheye is translated to Fishauge in some places. But I guess Fisheye-Objektiv would be more appropriate?

**Comment by temran** [comment]
None of them.
https://de.wikipedia.org/wiki/Fischaugenobjektiv
In German translation "Fischaugenobjektiv" would be appropiate.


Am Di., 6. Nov. 2018 um 12:39 Uhr schrieb joostn <notifications@github.com>:

**Comment by joostn** [comment]
Ok, changed to Fischaugenobjektiv everywhere:
https://github.com/newhousenl/ptgui_localization/commit/3ab379d335faf95a02bbc9ca068b5321ff02e89f

And Linse and Objektiv were used interchanged, I've changed this to Objektiv everywhere:
https://github.com/newhousenl/ptgui_localization/commit/964a86353d525dc317a598bf33813fe50dc32992

**Pull request merged**
